services:
  - type: web
    name: line-gpt-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python webhook.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: LINE_CHANNEL_SECRET
        sync: false
      - key: LINE_ACCESS_TOKEN
        sync: false